### ISSUE TITLE
请问这个怎么用啊？

### ISSUE THREAD

**Issue by Suitear** [457452950/YanXiuWang#1]
请问适配yanxiu网的吗？加不了你Q啊

**Comment by MaybeNullPtr** [comment]
QQ加好友的话需要报明来意，我一般看到没有的就直接pass了。这个就是为yxw刷课做的，不是适配yanxiuwang。如果可以可以告诉我你有没有编程基础，以便我更好的帮助你使用。另：造成的不良后果我将不承担。

**Comment by Suitear** [comment]
感谢回复，我是为了在yanxiu网刷课，很头疼啊，以前的油猴脚本都没用了。没有编程基础，不过能看懂一些油猴脚本，加你Q需要回答问题。请问有没有Telegram可以联络啊
![image](https://github.com/457452950/YanXiuWang/assets/9960618/1b44612e-1b45-4054-bc76-1ab9830f7bda)


我在win11上装了python 3.12.3， 也装了需要的其他模块， 但是不知道咋用呀。
![image](https://github.com/457452950/YanXiuWang/assets/9960618/6a753106-023f-4037-8ad0-72daba2040a8)

**Comment by MaybeNullPtr** [comment]
非常悲伤的告诉你，我们看网课的网站不是同一个，是不兼容的，我使用的是我们当地的zs市yxw。我实在没想到yxw也有好多个。抱歉，我得修改下我的仓库名了，这个名字具有一定的迷惑性。
另：我不用T，QQ主要是验证信息，不要求正确的。

**Comment by Suitear** [comment]
应该是子域名的差别吧，具体播放观看的页面不都是 类似
https://ipx.yanxiu.com/grain/course/8685646992565137944/detail?projectId=6289627417675675432&phaseId=8657970790979665959&toolId=8685645155053404183&courseSourceId=34452&role=99
这样的吗

**Comment by MaybeNullPtr** [comment]
是这个 https://m.zsjsjy.com/  
![image](https://github.com/457452950/ZhongShanCityYanXiuWang/assets/69505320/efbee1e0-1459-48ae-9475-90a50d6d44b1)
